CREATE DATABASE IF NOT EXISTS bootcamp;

USE bootcamp;

DROP TABLE IF EXISTS USERS;

CREATE TABLE users(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    age INT NOT NULL,
    emaIl VARCHAR(50) NOT NULL,
    country VARCHAR(20) NOT NULL,
    cp VARCHAR(20) NOT NULL,
    gender ENUM('male', 'female') NOT NULL DEFAULT 'female',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);